progetto_home/multiplayer_chess/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'multiplayer_chess'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('home/', views.home, name='home'),
    path('edit/', views.edit, name='edit'),
    path('password-change/', views.my_password_change_view, name='password_change'),
    path("lobby/<str:mode>/", views.lobby, name="lobby"),
    path("<str:variant>/<str:room_number>/", views.chess_game, name="chess_game"),
    path("<str:variant>/<str:room_number>/get_position/", views.get_position, name="get_position"),
    path('cronologia/', views.cronologia, name='cronologia'),
    path("tournament-list/", views.tournament_list, name='tournament_list'),
    path("tournament/view/<str:tour_id>/", views.tournament_details, name='tournament_details'),
    path("tournament/view/<str:tour_id>/sub", views.tournament_subscribe, name='tournament_subscribe'),
    path("tournament/view/<str:tour_id>/unsub", views.tournament_unsubscribe, name='tournament_unsubscribe'),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    #----------------------------------------------------------------------------------------------------
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

progetto_home/project_chess/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('multiplayer_chess.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    

progetto_home/multiplayer_chess/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import PasswordChangeForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control form-control-lg'
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('questa e-mail è già registrata; riprovare.')
        return data

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove text
        self.fields['new_password1'].help_text = None

    def clean(self):
        return super().clean()

progetto_home/multiplayer_chess/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.http import HttpResponse
from .forms import LoginForm, RegisterForm, UserEditForm, ProfileEditForm, CustomPasswordChangeForm
from .models import Profile, Game, ChessTournament
from .filters import FilterCronologia
import json
import re
from django.urls import reverse
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.views.decorators.http import require_GET, require_http_methods


LOGIN_PATH = 'multiplayer_chess:login'
HOME_PATH = 'multiplayer_chess:home'
DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
TOURNAMENT_DETAILS_PATH = 'multiplayer_chess:tournament_details'

#OK
@require_GET
def index(request):
    if request.user.is_authenticated:
        return redirect(HOME_PATH)
    return redirect(LOGIN_PATH)

#OK
@require_http_methods(['GET', 'POST'])
def login_view(request):
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(HOME_PATH)
        else:
            messages.error(request, "username o password errati; riprovare.")
    form = LoginForm()
    return render(request=request, template_name="multiplayer_chess/login.html", context={"login_form": form})

#OK
@require_GET
def logout_view(request):
    logout(request)
    messages.success(request, "hai eseguito il log-out con successo.")
    return redirect(LOGIN_PATH)

#OK
@require_http_methods(['GET', 'POST'])
def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            messages.success(request, "registrazione avvenuta con successo; adesso, acceda al suo profilo.")
            return redirect(LOGIN_PATH)
        else:
            html_error = form.errors.as_text()
            new_html_error = re.sub(r'\*[^*]+\*', '', html_error).strip()
            messages.error(request, f"qualcosa è andato storto durante la registrazione: {new_html_error}")
    form = RegisterForm()
    return render(request=request, template_name="multiplayer_chess/register.html", context={"register_form": form})

#OK
@require_GET
@cache_control(no_cache=True, max_age=1)
def home(request):  
    if request.user.is_authenticated:
        return render(request=request, template_name='multiplayer_chess/home.html')
    elif 'username' in request.COOKIES and 'password' in request.COOKIES:
        username = request.COOKIES['username']
        password = request.COOKIES['password']
        user = authenticate(username=username, password=password)
        if user is None:
            user_created =get_user_model().objects.create_user(
                username=username,
                password=password,
            )
            Profile.objects.create(
                user=user_created,
            )   
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request=request, template_name='multiplayer_chess/home.html')
        else:
            return redirect(LOGIN_PATH)
    else:
        return redirect(LOGIN_PATH)

#OK
@require_http_methods(['GET', 'POST'])
@login_required(login_url='/login')
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        try:
            user_form.save()
            profile_form.save()
            messages.success(request, "profilo modificato con successo.")
        except Exception:
            messages.error(request, "qualcosa è andato storto durante la modifica; riprovare.")
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'multiplayer_chess/edit.html', context={'user_form': user_form, 'profile_form': profile_form})

#OK
@require_http_methods(['GET', 'POST'])
@login_required(login_url='/login')
def my_password_change_view(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Password modificata con successo, è necessario riautenticarsi.")
            return redirect(LOGIN_PATH)
        else:
            messages.error(request, "qualcosa è andato storto durante la modifica; riprovare.")
    else:
        form = CustomPasswordChangeForm(user=request.user)
    return render(request, 'multiplayer_chess/password_change.html', {'form': form})

#OK
@require_GET
@cache_control(no_cache=True)
@login_required(login_url='/login')
def lobby(request, mode):
    

    partite_in_corso = Game.objects.filter(
        Q(player1=request.user) | Q(player2=request.user),
        status='started',
    )
    partita = partite_in_corso.first()
    if partite_in_corso.count() > 0:
        messages.error(
            request, 
            mark_safe(
                'Non puoi iniziare una nuova partita se ne hai una ancora in corso. \
                Clicca <a href="{}">qui</a> per continuare la tua partita.' \
                .format(reverse_lazy('multiplayer_chess:chess_game', args=[partita.mode, partita.room_id])))
            )
        return redirect(HOME_PATH)


    modes = ('classic', 'atomic', 'antichess', 'kingofthehill', 'threecheck', 'horde', 'racingkings')
    if mode not in modes:
        messages.error(request, "Variante non disponibile")
        return redirect(HOME_PATH)
    return render(request, "multiplayer_chess/lobby.html" , {'mode': mode})

#OK
@require_GET
@login_required(login_url='/login')
def cronologia(request):
    username = request.user
    cronologia1 = Game.objects.filter(player1=username)
    cronologia2 = Game.objects.filter(player2=username)
    cronologia = (cronologia1 | cronologia2)
    cro_filtrata = FilterCronologia(request.GET, queryset=cronologia)
    ctx = {'cronologia': cro_filtrata , 'username': username}
    return render(request, "multiplayer_chess/cronologia.html", ctx)

#-------------------------------------------------------------------------------------------------------------------------------------------
#OK
@require_GET
@cache_control(no_cache=True)
@login_required(login_url='/login')
def chess_game(request, room_number, variant):

    games = Game.objects.filter(room_id=room_number)
    game = games.first()
    user = request.user

    if user not in [game.player1, game.player2]:
        messages.error(request, "Non fai parte di questa lobby")
        return redirect(HOME_PATH)
    
    if game.status == 'finished':
        messages.error(request, "La partita è terminata")
        return redirect(HOME_PATH)
        
    order = 1 if game.player1 == user else 2

    profiles1 = Profile.objects.filter(user_id=game.player1)
    profiles2 = Profile.objects.filter(user_id=game.player2)

    profile1 = profiles1.first()
    username1 = game.player1.username
    profile2 = profiles2.first()
    username2 = game.player2.username

    if order == 1:
        elo_player1 = getattr(profile1, f"elo_{variant}", 0)
        elo_player2 = getattr(profile2, f"elo_{variant}", 0)
    else:
        elo_player1 = getattr(profile2, f"elo_{variant}", 0)
        elo_player2 = getattr(profile1, f"elo_{variant}", 0)
        #scambio le 4 variabili tra di loro
        profile2 , profile1 = profile1 , profile2
        username2 , username1 = username1, username2
        
    ctx = {
        "title" : "Partita scacchi",
        "order": order,
        "room_number": room_number,
        'username': username1,
        'user_image': profile1.photo,
        'user_elo1': elo_player1,
        'username2': username2,
        'user2_image': profile2.photo,
        'user_elo2': elo_player2,
        'variant': variant,
    }
    return render(request, template_name="multiplayer_chess/chess_game.html", context=ctx)

#OK
@require_GET
def get_position(request, variant, room_number):
    # Get the position here
    game = Game.objects.get(pk=room_number)
    fen = game.fen
    turn = game.turn
    position = {'fen': fen, 'turn':turn}
    response_data = json.dumps(position)
    return HttpResponse(response_data, content_type='application/json')

@require_GET
def tournament_list(request):
    all_tournaments = ChessTournament.objects.all()
    tournament_list = []
    for tournament in all_tournaments:
        tournament_dict = {
            'id': tournament.pk,
            'name': tournament.name,
            'start_date': tournament.start_datetime.strftime(DATE_FORMAT),
            'end_date': tournament.end_datetime.strftime(DATE_FORMAT),
            'players': tournament.players.count(),  
            'variante': tournament.mode,
            'tier': tournament.tier
        }
        tournament_list.append(tournament_dict)
    return render(request, template_name="multiplayer_chess/tournament_list.html", context={'tournaments': tournament_list})

@require_GET
def tournament_unsubscribe(request, tour_id):
    tournament = ChessTournament.objects.get(pk=tour_id)
    if tournament.status != 'iscrizione':
        messages.error(request, "Iscrizioni chiuse")
        return redirect(reverse(TOURNAMENT_DETAILS_PATH, kwargs={'tour_id': tour_id}))

progetto_home/multiplayer_chess/templates/multiplayer_chess/home.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block title %} {{title}} {% endblock %}

{% block navbar %}
    {% include 'multiplayer_chess/navbar.html' %}
{% endblock %}

{% block content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {{ message }}
            </div>
            {% elif message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {{ message }}
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <style>
        .container {
            max-width: 1500px;
        }
    </style>

    <div class="container my-3">
        <!-- First row -->
        <div class="row first-row">
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/chess_classic.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='classic' %}" class="btn primary_bg stretched-link">Gioca a scacchi classici</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/anti_chess.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='antichess' %}" class="btn primary_bg stretched-link">Gioca a scacchi vinciperdi</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/king_of_the_hill_chess.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='kingofthehill' %}" class="btn primary_bg stretched-link">Gioca a scacchi king of the hill</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/atomic_chess.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='atomic' %}" class="btn primary_bg stretched-link">Gioca a scacchi atomici</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Second row -->
        <div class="row second-row">
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/three_check_chess.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='threecheck' %}" class="btn primary_bg stretched-link">Gioca a scacchi 3-check</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/horde_chess.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='horde' %}" class="btn primary_bg stretched-link">Gioca a scacchi orda</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/racing_kings_chess.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="{% url 'multiplayer_chess:lobby' mode='racingkings' %}" class="btn primary_bg stretched-link">Gioca a scacchi racing kings</a>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-3 mx-auto my-3 text-center">
                <div class="card">
                    <img style="max-height: 333px;" src="{% static 'multiplayer_chess/images/chess_friend.jpg' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <a href="#" class="btn primary_bg stretched-link">Gioca a scacchi ...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

progetto_home/multiplayer_chess/templates/multiplayer_chess/login.html
{% extends 'multiplayer_chess/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'multiplayer_chess/form.css' %}">
{% endblock %}

{% block content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
      </div>
    {% elif message.tags == 'success' %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

<section>
  <div class="container py-3 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;">
                  <div class="row g-0">
                      <div class="col-md-6 col-lg-5 d-none d-md-flex">
                          <img src="https://images.pexels.com/photos/4973821/pexels-photo-4973821.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
                              alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                      </div>
                      <div class="col-md-6 col-lg-7 d-flex align-items-center">
                          <div class="card-body p-4 p-lg-5 text-black">
                              <form method="post">
                                  {% csrf_token %}
                                  <div class="d-flex align-items-center mb-3 pb-1">
                                      <span class="h1 fw-bold mb-0">&#9823; Chess</span>
                                  </div>
                                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>
                                  <div class="form-outline mb-4">
                                      <label class="form-label" for="id_username">Username</label>
                                      {{ login_form.username }}
                                  </div>
                                  <div class="form-outline mb-4">
                                      <label class="form-label" for="id_password">Password</label>
                                      {{ login_form.password }}
                                  </div>
                                  <div class="pt-1 mb-4 d-grid">
                                      <button class="btn btn-dark btn-lg" type="submit">Login</button>
                                      <a href="#" class="btn btn-success btn-lg mt-3" id="playAsGuestBtn">Play as Guest</a>
                                  </div>
                                  <a class="small text-muted" href="#">Forgot password?</a>
                                  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a style="color: #393f81;" href="{% url 'multiplayer_chess:register' %}">Register here</a></p>
                              </form>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

<script>
    document.getElementById("playAsGuestBtn").addEventListener("click", function(){
        // Generate a random username and password
        let randomUsername = "guest" + Math.floor(Math.random() * 10000000);
        let randomPassword = Math.floor(Math.random() * 1000000000).toString();

        // Set a cookie with the username and password that expires when the user closes their browser
        document.cookie = `username=${randomUsername}; expires=0; path=/`;
        document.cookie = `password=${randomPassword}; expires=0; path=/`;

        fetch('/home/', {
          method: 'GET'
        }).then(response => {
          // Redirect to /home/
          window.location.href = response.url;
        })
    });

</script>

{% endblock %}

progetto_home/multiplayer_chess/templates/multiplayer_chess/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand mb-1">&#9823; Chess</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
          <ul class="navbar-nav me-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'multiplayer_chess:home' %}">Gioca partita</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'multiplayer_chess:cronologia' %}">Cronologia</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'multiplayer_chess:leaderboard'%}">Leaderboard</a>
              </li> 
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'multiplayer_chess:tournament_list'%}">Tornei</a>
              </li>
          </ul>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <!-- User profile image -->
            <span class="navbar-text">
              {% if request.user.profile.photo %}
                <img src="{{ request.user.profile.photo.url }}" alt="User profile" class="rounded-circle mt-1 me-2" style="width: 32px; height: 32px;">
              {% else %}
                <img src="{% static 'multiplayer_chess/images/user.jpg' %}" alt="Default Image" class="rounded-circle mt-1 me-2" style="width: 32px; height: 32px;">
              {% endif %}
            </span>
          </li>
          
          
          <style>
            .dropdown-menu {
              width: 135px !important;
              min-width: 135px !important;
            }
          </style>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ request.user }}
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'multiplayer_chess:password_change' %}">Edit Password</a>
              <a class="dropdown-item" href="{% url 'multiplayer_chess:edit' %}">Edit Profile</a>
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'multiplayer_chess:logout' %}">logout</a>
          </li>

        </ul>
      </div>
  </div>
</nav>

progetto_home/multiplayer_chess/templates/multiplayer_chess/tournament_details.html
{% extends 'multiplayer_chess/base.html' %}

{% load static %}

{% block navbar %}
    {% include 'multiplayer_chess/navbar.html' %}
{% endblock %}

{% block css %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha384-NXgwF8Kv9SSAr+jemKKcbvQsz+teULH/a5UNJvZc6kP47hZgl62M1vGnw6gHQhb1" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://www.aropupu.fi/bracket/jquery-bracket/dist/jquery.bracket.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://www.aropupu.fi/bracket/jquery-bracket/dist/jquery.bracket.min.css">
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'multiplayer_chess/CSS/grafica_lobby.css' %}">


<h1 class="mt-3 text-center" style="color: white;">{{tournament_data.name}}</h1>
<div class="container mt-4" style="max-width: 1200px; border-radius: 20px; ">
    <div class="row">
        <h2 class="mb-4">Dettagli Torneo:</h2>
        <div class="col-md-6 mt-1">
            
            <ul>
                <li><strong>Nome:</strong> {{ tournament_data.name }}</li>
                <li><strong>Data Inizio:</strong> {{ tournament_data.start_date }}</li>
                <li><strong>Data Fine:</strong> {{ tournament_data.end_date }}</li>
            </ul>
        
            <p style="margin-bottom: 5px;">Giocatori:</p>
        
            <ul>
                {% for player in tournament_data.players %}
                    <li>{{ player }}</li>
                {% empty %}
                    <li>No players yet.</li>
                {% endfor %}
            </ul>
    
        </div>
        
        {% if tournament_status != 'iscrizione' %}
            <div class="col-md-6">
                <div id="minimal">
                    <script>
                        var players_array = {{players_list|safe}};
                        var results = {{results|safe}};
                        console.log(players_array);
                        console.log(results)
                        var bigData = {
                            "teams":       
                                players_array,
                            "results": [            
                                results
                            ]
                        }
        
                        $.noConflict();
                        jQuery(function($) {
                            $('div#minimal .demo').bracket({init: bigData, skipConsolationRound: true});
                        });//skipConsolationRound: true
        
                    </script>
                    <div class="demo"></div>
                </div>
            </div>
        {% endif %}
    </div>

    {% if tournament_status != 'iscrizione'%}
        <div class="row mt-4">
            <div class="col">
                <a href="{% url 'multiplayer_chess:tournament_list'%}" role="button" class="btn btn-primary mb-2">Back to the list</a>
            </div>
            <div class="col">
                <a href="{% url 'multiplayer_chess:chess_game' room_number=match_user_id variant=mode %}" role="button" class="btn btn-primary">Vai alla tua partita  {{match_user}}</a>
            </div>
        </div>
    {% elif match_user_id == 0 %}
        <div class="row mt-4">
            <div class="col">
                <a href="{% url 'multiplayer_chess:tournament_list'%}" role="button" class="btn btn-primary mb-2">Back to the list</a>
            </div>
        </div>
    {% else %}
        <div class="row mt-4">
            <div class="col">
                <a href="{% url 'multiplayer_chess:tournament_list'%}" role="button" class="btn btn-primary mb-2">Back to the list</a>
                {% if iscritto %}
                    <p>
                        <a href="{% url 'multiplayer_chess:tournament_unsubscribe' tour_id=tournament_data.id %}" role="button" class="btn btn-primary">Disiscriviti dal Torneo</a>
                    </p>
                {% else %}
                    <p>
                        <a href="{% url 'multiplayer_chess:tournament_subscribe' tour_id=tournament_data.id %}" role="button" class="btn btn-primary">Iscriviti al Torneo</a>
                    </p>
                {% endif %}
            </div>
        </div>
    {% endif %}
</div>

{% endblock %}